version: '3.8'
services:
  nuxt-app:
    build: .
    container_name: nuxt_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - HOST=0.0.0.0
      - PORT=3000
    command: npm run dev