version: "3.8"

services:
  app:
    build: .
    container_name: nuxt_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./dev.db:/app/dev.db
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "preview"]